account/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('account.views', 
    url(r'register', 'register'),
    url(r'login', 'login'),
    url(r'logout', 'logout'),
    url(r'$', 'index'),
)

bitmart/urls.py
from django.conf.urls import patterns, include, url

from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$',         'bitmart.views.index'), 
    url(r'^account/',  include('account.urls')),
    url(r'^wallet/',   include('wallet.urls')),
    url(r'^listing/',  include('listing.urls')),
    url(r'^vendor/',   include('vendor.urls')),

    url(r'^admin/',    include(admin.site.urls)),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

listing/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('listing.views', 
    url(r'([\w\-]+)?$',     'index'),
    url(r'view/(\d+)$',     'view'),
    url(r'create$',         'create'),
    url(r'purchase/(\d+)$', 'purchase'),
)

wallet/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('wallet.views', 
    url(r'^$', 'index'),
    url(r'^create$', 'create'),
    url(r'^send$', 'send'),
)

account/models.py
from django.db import models
from django.contrib.auth.models import User
class Account(models.Model):
  user = models.ForeignKey(User, unique=True)
  pin = models.CharField(max_length=6)

listing/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib import admin
from vendor.models import Vendor
from django.template.defaultfilters import slugify
import zlib

class Category(models.Model):
  title  = models.CharField(max_length=64)
  parent = models.ForeignKey('self', null=True, blank=True)
  slug      = models.SlugField()

  def children(self):
    return self.category_set.all()
  sub_cats = property(children)

  def save(self, *a, **kw):
    self.slug = slugify(self.title)
    super(Category, self).save(*a, **kw)

  def __unicode__(self): return self.title


class Listing(models.Model):
  vendor    = models.ForeignKey(Vendor)
  title     = models.CharField(max_length=64)
  slug      = models.SlugField()
  description \
            = models.TextField()
  cost      = models.DecimalField(decimal_places=6,max_digits=6)
  image     = models.FileField(upload_to='listing')
  timestamp = models.DateTimeField(auto_now_add=True)

  def save(self, *a, **kw):
    self.slug = slugify(self.title)
    super(Listing, self).save(*a, **kw)

class ListingForm(ModelForm):
  class Meta:
    model = Listing
    fields = ['title','description','cost','image']

class Purchase(models.Model):
  buyer     = models.ForeignKey(User)
  listing   = models.ForeignKey(Listing)
  status    = models.CharField(max_length=64)
  timestamp = models.DateTimeField(auto_now_add=True)

  def safeid(self): return zlib.crc32(str(self.id))
  safe_id = property(safeid)

class Review(models.Model):
  buyer     = models.ForeignKey(User)
  listing   = models.ForeignKey(Listing)
  content   = models.TextField()
  timestamp = models.DateTimeField(auto_now_add=True)

admin.site.register(Category)
admin.site.register(Listing)
admin.site.register(Purchase)
admin.site.register(Review)

market/models.py
from django.db import models
from django.contrib import admin

class Prices(models.Model):
  currency  = models.CharField(max_length=3)
  day       = models.DecimalField(max_digits=16,decimal_places=2)
  week      = models.DecimalField(max_digits=16,decimal_places=2)
  month     = models.DecimalField(max_digits=16,decimal_places=2)
  timestamp = models.DateTimeField(auto_now=True)

  def __unicode__(s): return "%s < %s >" % (s.currency, s.day)

admin.site.register(Prices)

wallet/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User

account/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from account.models import Account
from listing.models import Listing
from vendor.models import Vendor
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout as _logout
from django.contrib.auth import login as _login

def index(request):
  isvendor = Vendor.is_vendor(request.user)
  if isvendor:
    listings = Listing.objects.filter(vendor=request.user)
  else:
    listings = []

  return render(request, 'account/index.html', {
    'username': request.user.username,
    'isvendor': isvendor,
    'listings': listings
  })

def login(req):
  msg = ''
  if req.method == 'POST':
    u = authenticate(username=req.POST['username'],password=req.POST['password'])
    if u != None:
      _login(req,u)
      return HttpResponseRedirect('/account/')
    else:
      msg = 'Invalid credentials'
  return render(req, 'account/login.html', {'msg':msg})

def logout(req):
  _logout(req)
  return HttpResponseRedirect('/')

def register(req):
  errors = {}
  if req.method == 'POST':
    d = req.POST
    un = d['username']
    pi = d['pin']
    p1 = d['password1']
    p2 = d['password2']

    valid = True

    if User.objects.filter(username=un).count() > 0:
      valid = False
      errors['username'] = 'Must be unique.'

    if len(pi) < 4 or len(pi) > 6:
      valid = False
      errors['pin'] = 'Must be between 4 and 6 characters.'

    if p1 != p2:
      valid = False
      m = 'Passwords must match.'
      errors['password1'] = m
      errors['password2'] = m

    if valid:
      new = User.objects.create_user(un,"%s@%s.io"%(un,un),p1)
      new.save()
      acc = Account(user=new,pin=pi)
      acc.save()

      user = authenticate(username=un, password=p1)
      if user != None:
        _login(req,user)
        return HttpResponseRedirect('/account/')
      else:
        return HttpResponseRedirect('/')
      
  
  return render(req, 'account/register.html', {
    'errors': errors   
  })

bitmart/views.py
from django.shortcuts import render, redirect

def index(request):
  return render(request, 'index.html', {})

listing/views.py
from django.shortcuts import render
from listing.models import *

def index(request, slug=''):
  selected = Category.objects.filter(slug=slug)
  if (selected.count()>0 and selected.first().parent != None):
    cats = selected
  else:
    cats = Category.objects.filter(parent=None)

  return render(request, 'listing/index.html', {
    'categories': cats,
    'category': slug
  })

def view(request):
  return render(request, 'listing/view.html', {})

def create(request):
  form = ListingForm()
  return render(request, 'listing/create.html', {
    'form': form
  })

def purchase(request):
  return render(request, 'listing/purchase.html', {})

market/views.py
from django.shortcuts import render

# Create your views here.

wallet/views.py
from django.shortcuts import render, redirect

import bitcoinrpc
bitrpc = bitcoinrpc.connect_to_remote('bitcoin', 'lolhax')

def create(request):
  addr = bitrpc.getnewaddress( request.user.username )
  return render(request, 'wallet/create.html', { 'address':addr })

def index(request):
  addresses = bitrpc.getaddressesbyaccount( request.user.username )
  bal = bitrpc.getbalance( request.user.username )
  
  return render(request, 'wallet/index.html', {
    'wallets': addresses,
    'balance': ('%.2f' % bal)
  })

def send(request):
  # whatever
  return render(request, 'wallet/send.html')

templates/base.html
{% load i18n %}

<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}BitMart{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- latest compiled and minified css -->
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-theme.min.css">

  <link rel="stylesheet" href="/static/style.css">


    
  {% block head %}
  {% endblock %}
  </head>
  <body>


   <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <span class="navbar-brand" href="#">BitMart</span>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li {% if pagename == "home" %}class="active"{% endif %}><a href="/">Home</a></li>
            <li {% if pagename == "vendor" %}class="active"{% endif %} ><a href="/vendor">Vendors</a></li>
            <li {% if pagename == "listing" %}class="active"{% endif %} ><a href="/listing">Listings</a></li>
<!--
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
              </li> -->
          </ul>



<ul class="nav navbar-nav navbar-right">
	{% if user.is_authenticated %}
	<li {% if pagename == "account" %}class="active"{% endif %} ><a href="/account">{{ user.username }}</a></li>
	<li><a href="{% url 'account.views.logout' %}">{% trans "Log out" %}</a></li>

	{% else %}
	<li><a href="{% url 'account.views.login' %}">{% trans "Log in" %}</a></li>
	{% endif %}
</ul>

        </div><!--/.navbar-collapse -->
      </div>
    </div>

    {% block header %}
    {% endblock %}

    <div class="container bitmart">


  {% block content %}
    Test page please ignore
  {% endblock %}
      </div>

      <hr>

      <footer>
        <p>&copy; BitMart 2013</p>
      </footer>
    </div> <!-- /container -->






    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="//code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->

  <!-- Latest compiled and minified JavaScript -->
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% load i18n %}

{% block header %}

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>BitMart</h1>
        <h2>A new road into the future.</h2>
        <p>Are you ready to witness a revolution?</p>
        <p><a class="btn btn-primary btn-lg" href="/accounts/login">Sign Up &raquo;</a></p>
      </div>
    </div>

{% endblock %}

{% block content %}

<p>BitMart currently hosts 218 vendors, listing 2193 unique products. Start browsing now!</p>

{% endblock %}

templates/listing/create.html
{% extends 'base.html' %}

{% block content %}
    <form role="form" action="" method="post" enctype="multipart/form-data">
    {{ form.non_field_errors }}
    
    <div class="form-group">
      <label for="id_title">Title</label>
      {{ form.title }} 
    </div>
    <div class="form-group">
      <label for="id_description">Description</label>
      {{ form.description }} 
    </div>

    <div class="form-group">
      <label for="id_cost">Cost</label>
      {{ form.cost }} 
    </div>

    <div class="form-group">
      <label for="id_image">Image</label>
      {{ form.image }} 
    </div>



    </form>
{% endblock %}

templates/listing/index.html
{% extends 'base.html' %}

{% block content %}


      <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>
          <div class="jumbotron">
            <h1>BitMart Listings</h1>
            <p>Select a category on the right to begin browsing listings!</p>
          </div>
          <div class="row">
            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Drugs</h2>
              <p>From Cannabis to painkillers to ketamine, we have it all. Vendor offerings vary by season. Please make sure to leave a review after ordering so others can go off of your experiences.</p>
              <p><a class="btn btn-default" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Forgeries</h2>
              <p>Fake IDs, new personas. All you need to start a new life. Try not to get caught with one of these, however. Major felony status.</p>
              <p><a class="btn btn-default" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Hardware</h2>
              <p>Need PC components? We have your back. Ready to get into or out of bitcoin mining? Why not try your hand at selling GPUs here?</p>
              <p><a class="btn btn-default" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Food</h2>
              <p>Food from everywhere. Kinder eggs, lead-chickens from Korea. Whatever the fuck you want.</p>
              <p><a class="btn btn-default" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Digital Goods</h2>
              <p>Maybe someone hacked a db and is selling passwords or a stupid vesion of Linux that should be free anyway. IDK, I never go in here.</p>
              <p><a class="btn btn-default" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <!--
            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Custom Orders</h2>
              <p>Orders just for you, vendors can agree to make listings specifically at your request. Bon appetit.</p>
              <p><a class="btn btn-default" href="#">View details &raquo;</a></p>
            </div><!--/span-- >
            -->
          </div><!--/row-->
        </div><!--/span-->


        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
          <div class="well sidebar-nav">
            <ul class="nav">
              {% for cat in categories %}
              <li><a class="main" href="{% url 'listing.views.index' cat.slug %}">{{ cat.title }}</a></li>
                {% if category == cat.slug %}
                  {% for sub in cat.sub_cats %}
                  <li><a href="{% url 'listing.views.index' sub.slug %}">{{ sub.title }}</a></li>
                  {% endfor %}
                {% endif %}
              {% endfor %}
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

{% endblock %}

templates/wallet/create.html
{% extends 'base.html' %}

{% block content %}

Your new btc address is {{ address }}

<a href="{% url 'wallet.views.index' %}">view wallets</a>
{% endblock %}

templates/wallet/index.html
{% extends 'base.html' %}

{% block content %}
<p>
Total balance: {{ balance }} btc</p>

Wallet addresses:
{{ wallets }}

<hr />

  <a href="{% url 'wallet.views.create' %}">New wallet</a> | <a href="{% url 'wallet.views.send' %}">Cash out</a>
{% endblock %}

templates/wallet/send.html
{% extends 'base.html' %}

{% block content %}

<h2>Send coins</h2>

<form role="form">
  <div class="form-group">
    <label for="id_amount">Amount</label>
    <input class="form-control" id="id_amount" placeholder="Amount to send">
  </div>
  <div class="form-group">
    <label for="id_pin">PIN</label>
    <input type="password" class="form-control" id="id_pin" placeholder="PIN">
  </div>
  <div class="checkbox">
    <label>
      <input type="checkbox"> Are you sure?
    </label>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>

<hr />

<a href="{% url 'wallet.views.index' %}">Wallets</a>
{% endblock %}